language: go

go:
  - 1.12.x

git:
  depth: 1

go_import_path: code.cloudfoundry.org/eirini-staging

# Install dependencies responsible for testing/linting
before_install:
    - go get -u github.com/onsi/ginkgo/ginkgo
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.15.0

# Skip install step; use vendored dependencies
install: true

script:
    - make test
    - make lint
